### PR TITLE
Add MustParseSchema function

### PR DESCRIPTION
**Pull request by spenczar**
I found myself creating an app-global schema. I want to parse it once. A failure to parse is such a critical error that we should just panic immediately.

### CODE REVIEW

**Comment by serejja** [comment]
Hey @spenczar I'm not quite sure it's worth adding such function as it saves like 3 lines of code but may make API a bit cluttered. If you feel like folks would really use that - please update the PR against the updated master.

Thanks!

**Comment by aviflax** [comment]
I’m new to go but my 2¢ from what I’ve learned so far: it seems maybe not so idiomatic for library code to panic? The idiom I’ve seen in most APIs, including the stdlib, is to just return an error that should be checked. It feels more like the domain of application code to decide to panic if an error occurs when parsing a schema.

**Comment by spenczar** [comment]
The `Must*` pattern is quite common in the Go standard library:

 - [regexp.MustCompile](http://golang.org/pkg/regexp/#MustCompile), for when a regular expression simply must be valid.
 - [html/template.Must](http://golang.org/pkg/html/template/#Must), for when a template file absolutely has to exist to proceed sensibly.
 - [language.MustParseBase](https://godoc.org/golang.org/x/text/language#MustParseBase), for when parsing language tags. This one has a CR with [approval from Rob Pike](https://codereview.appspot.com/65380043/) himself.

`panic` is *definitely* not something you want to throw around very often, but `Must` functions are one of the exceptions - like `log.Fatal`, they ought to only be invoked in `package main` for this reason.

But yeah, it's possible to leave this out of the library. I just imagine it would be a very common usage.

**Comment by serejja** [comment]
Ok, this totally makes sense to me. I think there's a lot of scenarios when being unable to parse a schema is a fatal error.
I suppose once you update the PR we can accept it.

Thanks

**Pull request merged**
